/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.lentrix.storemanager;

import com.lentrix.storemanager.db.DB;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.time.format.FormatStyle;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author lentrix
 */
public class ByTransactionDailyReport extends javax.swing.JPanel {
    
    LocalDate dateNow = LocalDate.now();
    float total=0f;
    /**
     * Creates new form ByTransactionDailyReport
     */
    public ByTransactionDailyReport() {
        initComponents();
        
        dateLabel.setText(dateNow.format(DateTimeFormatter.ofPattern("MMMM dd, yyyy")));
            
        String query = 
            "SELECT users.username, sales.id, sales.time, sales.discount, "
                + "SUM(sales_items.qty*sales_items.price) AS 'total' " +
            "FROM sales " +
            "LEFT JOIN sales_items ON sales_items.sales_id=sales.id " +
            "LEFT JOIN users ON sales.user_id=users.id " +
            "WHERE sales.date = ? " +
            "GROUP BY sales_items.id";
        
        Connection conn = DB.connect();
        try {
            PreparedStatement ps = conn.prepareStatement(query);
            ps.setString(1, dateNow.toString());
            ResultSet rs = ps.executeQuery();
            
            renderTable(rs);
        }catch(SQLException ex) {
            Helper.error(ex.getMessage(), this);
        }
    }
    
    private void renderTable(ResultSet rs) throws SQLException {
        String[] headers = {"Cashier", "Time", "Discount", "Total"};
        
        DefaultTableModel model = new DefaultTableModel(headers, 0){
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        
        while(rs.next()) {
            model.addRow(new Object[] {
                rs.getString("username"),
                rs.getTime("time").toLocalTime().format(DateTimeFormatter.ISO_LOCAL_TIME),
                rs.getFloat("discount"),
                rs.getFloat("total")
            });
            
            total+=rs.getFloat("total");
        }
        
        jTable1.setModel(model);
        totalLabel.setText(String.format("%,.2f", total));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        dateLabel = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        totalLabel = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel1.setText("By Transaction Daily Report:");

        dateLabel.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        dateLabel.setText("May 9, 2021");

        jPanel1.setLayout(new java.awt.BorderLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        totalLabel.setFont(new java.awt.Font("Raleway", 0, 36)); // NOI18N
        totalLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        totalLabel.setText("0.00");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(dateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 337, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(totalLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(dateLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 342, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(totalLabel)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel dateLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel totalLabel;
    // End of variables declaration//GEN-END:variables
}
