/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.lentrix.storemanager;

import com.lentrix.storemanager.db.ItemController;
import com.lentrix.storemanager.models.CustomerModel;
import com.lentrix.storemanager.models.ItemModel;
import com.lentrix.storemanager.models.SalesItemModel;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author lentrix
 */
public class POSTerminal extends javax.swing.JFrame {
    List<SalesItemModel> salesItems;
    boolean isWholesale;
    CustomerModel customer;
    /**
     * Creates new form POSTerminal
     */
    public POSTerminal() {
        initComponents();
        
        barCodeField.setSelectionEnd(barCodeField.getText().length());
        
        setExtendedState(this.getExtendedState() | JFrame.MAXIMIZED_BOTH);
        
        cashierLabel.setText("Cashier: " + Helper.currentUser.getFullname());
        
        salesItems = new ArrayList<SalesItemModel>();
        
        isWholesale = true;
        customer = null;
        
        setVisible(true);
        
        refreshTable();
    }
    
    private void welcome() {
        refreshTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        clearIcon = new javax.swing.JLabel();
        quantityIcon = new javax.swing.JLabel();
        wsIcon = new javax.swing.JLabel();
        removeIcon = new javax.swing.JLabel();
        finalizeIcon = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        posMast = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        subTotalLabel = new javax.swing.JLabel();
        cashierLabel = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        barCodeField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        clearEntriesMenuItem = new javax.swing.JMenuItem();
        changeQuantityMenuItem = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        removeItemMenuItem = new javax.swing.JMenuItem();
        finalizeTransactionMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(214, 243, 246));

        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        jPanel1.setLayout(new java.awt.BorderLayout(10, 5));

        jPanel2.setLayout(new java.awt.GridLayout(6, 1, 0, 5));

        clearIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/lentrix/storemanager/icons/f1-clear.png"))); // NOI18N
        clearIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clearIconMouseClicked(evt);
            }
        });
        jPanel2.add(clearIcon);

        quantityIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/lentrix/storemanager/icons/f2-quantity.png"))); // NOI18N
        quantityIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                quantityIconMouseClicked(evt);
            }
        });
        jPanel2.add(quantityIcon);

        wsIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/lentrix/storemanager/icons/f3-ws_retail.png"))); // NOI18N
        wsIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                wsIconMouseClicked(evt);
            }
        });
        jPanel2.add(wsIcon);

        removeIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/lentrix/storemanager/icons/f4-remove.png"))); // NOI18N
        removeIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                removeIconMouseClicked(evt);
            }
        });
        jPanel2.add(removeIcon);

        finalizeIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/lentrix/storemanager/icons/f12-finalize.png"))); // NOI18N
        finalizeIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                finalizeIconMouseClicked(evt);
            }
        });
        jPanel2.add(finalizeIcon);

        jPanel1.add(jPanel2, java.awt.BorderLayout.LINE_START);

        jPanel3.setPreferredSize(new java.awt.Dimension(986, 70));
        jPanel3.setLayout(new java.awt.BorderLayout());

        posMast.setBackground(new java.awt.Color(1, 1, 1));
        posMast.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/lentrix/storemanager/icons/pos_mast.png"))); // NOI18N
        jPanel3.add(posMast, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel3, java.awt.BorderLayout.PAGE_START);

        subTotalLabel.setFont(new java.awt.Font("DejaVu Sans", 0, 36)); // NOI18N
        subTotalLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        subTotalLabel.setText("Sub Total: P0.00");

        cashierLabel.setText("Cashier: Name of Cashier");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cashierLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(266, 266, 266)
                .addComponent(subTotalLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 511, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(subTotalLabel)
                    .addComponent(cashierLabel))
                .addContainerGap())
        );

        jPanel1.add(jPanel4, java.awt.BorderLayout.PAGE_END);

        jPanel5.setLayout(new java.awt.BorderLayout(5, 0));

        jLabel2.setText("Bar Code:");

        barCodeField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barCodeFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(barCodeField, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(611, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(barCodeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel5.add(jPanel6, java.awt.BorderLayout.PAGE_START);

        jTable1.setFont(new java.awt.Font("DejaVu Sans", 0, 16)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {}
            },
            new String [] {

            }
        ));
        jTable1.setRowHeight(24);
        jScrollPane1.setViewportView(jTable1);

        jPanel5.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel5, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jMenu1.setText("Administration");

        jMenuItem4.setText("Daily Report");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuItem5.setText("Monthly Report");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem5);

        jMenuItem1.setText("Open Administration");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);
        jMenu1.add(jSeparator1);

        jMenuItem2.setText("Exit");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Transaction");

        clearEntriesMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        clearEntriesMenuItem.setText("Clear Entries");
        clearEntriesMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearEntriesMenuItemActionPerformed(evt);
            }
        });
        jMenu2.add(clearEntriesMenuItem);

        changeQuantityMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, 0));
        changeQuantityMenuItem.setText("Change Quantity");
        changeQuantityMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeQuantityMenuItemActionPerformed(evt);
            }
        });
        jMenu2.add(changeQuantityMenuItem);

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F3, 0));
        jMenuItem3.setText("Wholesale / Retail");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        removeItemMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, 0));
        removeItemMenuItem.setText("Remove Item");
        removeItemMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeItemMenuItemActionPerformed(evt);
            }
        });
        jMenu2.add(removeItemMenuItem);

        finalizeTransactionMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F12, 0));
        finalizeTransactionMenuItem.setText("Finalize Transaction");
        finalizeTransactionMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finalizeTransactionMenuItemActionPerformed(evt);
            }
        });
        jMenu2.add(finalizeTransactionMenuItem);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void barCodeFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barCodeFieldActionPerformed
        try {
            ItemModel item = ItemController.findCode(barCodeField.getText());
            if(item!=null) {
                SalesItemModel salesItem = new SalesItemModel(-1, item, 1, true);
                salesItem.getPrice();
                
                salesItems.add(salesItem);
                refreshTable();
                barCodeField.setText(null);
                barCodeField.grabFocus();
            }else {
                Helper.error("The barcode cannot be found.", this);
            }
        }catch(SQLException ex) {
            Helper.error(ex.getMessage(), this);
        }
    }//GEN-LAST:event_barCodeFieldActionPerformed

    private void clearIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearIconMouseClicked
        clear();
    }//GEN-LAST:event_clearIconMouseClicked

    private void quantityIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_quantityIconMouseClicked
        changeQty();
    }//GEN-LAST:event_quantityIconMouseClicked

    private void wsIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_wsIconMouseClicked
        toggleWholesale();
    }//GEN-LAST:event_wsIconMouseClicked

    private void removeIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_removeIconMouseClicked
        remove();
    }//GEN-LAST:event_removeIconMouseClicked

    private void finalizeIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_finalizeIconMouseClicked
        finalizeSales();
    }//GEN-LAST:event_finalizeIconMouseClicked

    private void clearEntriesMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearEntriesMenuItemActionPerformed
        clear();
    }//GEN-LAST:event_clearEntriesMenuItemActionPerformed

    private void changeQuantityMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeQuantityMenuItemActionPerformed
        changeQty();
    }//GEN-LAST:event_changeQuantityMenuItemActionPerformed

    private void removeItemMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeItemMenuItemActionPerformed
        remove();
    }//GEN-LAST:event_removeItemMenuItemActionPerformed

    private void finalizeTransactionMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finalizeTransactionMenuItemActionPerformed
        finalizeSales();
    }//GEN-LAST:event_finalizeTransactionMenuItemActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        toggleWholesale();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        new ManagementFrame().setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        new DailyReportDialog(this, true).setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        new MonthlyReport(this, true).setVisible(true);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void remove() {
        int row = jTable1.getSelectedRow();
        row = row==-1?salesItems.size()-1:row;
        
        SalesItemModel salesItem = salesItems.get(row);
        
        int res = JOptionPane.showConfirmDialog(this, "Do you want to remove this item " + salesItem.getItem().getItemName() + "?", "Remove?", JOptionPane.YES_NO_OPTION);
        if(res==JOptionPane.YES_OPTION) {
            salesItems.remove(row);
            refreshTable();
        }else {
            barCodeField.grabFocus();
        }
    }
    
    private void toggleWholesale() {
        int row = jTable1.getSelectedRow();
        row = row==-1?salesItems.size()-1:row;
        
        SalesItemModel salesItem = salesItems.get(row);
        
        salesItem.setIsWholeSale(!salesItem.isIsWholeSale());
        salesItem.renewPrice();
        
        refreshTable();
    }
    
    private void clear() {
        int res = JOptionPane.showConfirmDialog(this, "Do you want to clear all the items?", "Clear All?", JOptionPane.YES_NO_OPTION);
        if(res==JOptionPane.YES_OPTION) {
            salesItems.clear();
            refreshTable();
        }
    }
    
    private void changeQty() {
        int row = jTable1.getSelectedRow();
        row = row==-1?salesItems.size()-1:row;
        try {
            String input = JOptionPane.showInputDialog(this, "Enter new quantity:");
            if(input==null || input.isBlank()) {
                return;
            }
            
            int qty = Integer.parseInt(input);
            
            SalesItemModel salesItem = salesItems.get(row);
            
            salesItem.setQty(qty);
            
            refreshTable();
        }catch(NumberFormatException ex) {
            Helper.error("You entered an valid quantity value.", this);
        }
    }
    
    private void finalizeSales() {
        new FinalizeDialog(this, true,salesItems).setVisible(true);
        refreshTable();
    }
    
    /**
     * Change customer for future additional feature
     */
    private void changeCustomer() {
        
    }
    
    private void refreshTable() {
        String[] headers = {"Item", "Description", "Price", "Qty", "Amount"};
        DefaultTableModel model = new DefaultTableModel(headers, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        
        float subTotal = 0f;
        
        for(SalesItemModel salesItem: salesItems) {
            float price = salesItem.isIsWholeSale() ? salesItem.getItem().getWsPrice() : salesItem.getItem().getRtPrice();
            float amount = price * salesItem.getQty();
            subTotal += amount;
            String retailIndicator = salesItem.isIsWholeSale() ? "" : " (R)";
            model.addRow(new Object[] {
                salesItem.getItem().getItemName() + retailIndicator,
                salesItem.getItem().getItemDescription(),
                String.format("%,.2f", price),
                salesItem.getQty(),
                String.format("%,.2f", amount)
            });
        }
        
        jTable1.setModel(model);
        
        jTable1.getColumnModel().getColumn(0).setMinWidth(150);
        jTable1.getColumnModel().getColumn(1).setMinWidth(350);
        DefaultTableCellRenderer rightRenderer = new DefaultTableCellRenderer();
        rightRenderer.setHorizontalAlignment(JLabel.RIGHT);
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(JLabel.CENTER);
        jTable1.getColumnModel().getColumn(2).setCellRenderer(rightRenderer);
        jTable1.getColumnModel().getColumn(3).setCellRenderer(centerRenderer);
        jTable1.getColumnModel().getColumn(4).setCellRenderer(rightRenderer);
        
        subTotalLabel.setText(String.format("Sub Total: %,.2f", subTotal));
        
        barCodeField.grabFocus();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField barCodeField;
    private javax.swing.JLabel cashierLabel;
    private javax.swing.JMenuItem changeQuantityMenuItem;
    private javax.swing.JMenuItem clearEntriesMenuItem;
    private javax.swing.JLabel clearIcon;
    private javax.swing.JLabel finalizeIcon;
    private javax.swing.JMenuItem finalizeTransactionMenuItem;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel posMast;
    private javax.swing.JLabel quantityIcon;
    private javax.swing.JLabel removeIcon;
    private javax.swing.JMenuItem removeItemMenuItem;
    private javax.swing.JLabel subTotalLabel;
    private javax.swing.JLabel wsIcon;
    // End of variables declaration//GEN-END:variables
}
